FROM python:3.10-slim-buster as builder

WORKDIR /backend-flask

COPY requirements.txt requirements.txt

RUN pip3 wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt


FROM python:3.10-slim-buster

COPY --from=builder /wheels /wheels

RUN pip install --no-cache /wheels/*

COPY . .

ENV FLASK_ENV=development

EXPOSE ${PORT}

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]